### ISSUE TITLE
Clear up error code 401.

### ISSUE THREAD

**Issue by Zegnat** [PhotoBackup/api#2]
Currently error code 401 is used both when the server is misconfigured (no password has been set) and when the request was incomplete (not `upfile` was included). Server problems like the misconfigured password should really all go in the 5xx, 4xx codes are client errors.

For version 3 of the API these should really be split up.

For version 2 of the API the description of the 401 response on `/test` should clarify it is specifically about the server configuration and not about the client forgetting to send a password.

---

Sidenote: [PhotoBackup/server-bottle](https://github.com/PhotoBackup/server-bottle) currently does not follow the API, by responding with 401 on `/` if the server is misconfigured. 401 is described in the API as the error code for missing `upfile`. Either the Python server implementation has to be changed or the API has to be updated to add this secondary meaning for `/`.

**Comment by stephanepechard** [comment]
You're right, a bit of cleaning is necessary here... For the following, I tend to consider [HTTP statuses as defined here](http://httpstatus.es/). Also, I only consider the version 2 of the API.

Tell me if I'm wrong:
- 401 error is for "authentication is possible but has failed", so it should occur when the client did not provide the right password only ; your sidenote is correct, the Python server implementation is wrong on responding 401 on the absence of password in the config file... I think that something like 501 "server does not recognise method or lacks ability to fulfill" would be better, don't you think?
- the absence of password (or any other parameter) should be 400 "request cannot be fulfilled due to bad syntax" ? I don't find anything suitable for a specific lack of parameter ;

Feel free to update either API v2 or v3 to reflect this. Maybe creatng a v3 for such small adjustments is not necessarily, especially if we consider it was released yesterday :-)
Then, each maintainer should try to respect the highest version in code. That's the purpose of the API compatibility tables I try to maintain.

Do you see anything else?
Thanks for your sharp eye on the topic!!

**Comment by Zegnat** [comment]
> 401 error is for "authentication is possible but has failed", so it should occur when the client did not provide the right password only

Yes, `401 Unauthorized` is the right response for failed authentication attempts.

> I think that something like 501 "server does not recognise method or lacks ability to fulfill" would be better, don't you think?

No, `501 Not Implemented` usually means the client is trying to communicate with the server in a way the server does not understand. Or is trying to use some REST API that is planned for implementation but isn’t available yet. Uploading images is definitely implemented in all servers.

A misconfigured server is, AFAIK, always `500 Internal Server Error`. It happens when the server encounters something it never expected to happen, such as a misconfiguration. This is why faulty `.htaccess` files make Apache throw 500 errors.

> the absence of password (or any other parameter) should be 400 "request cannot be fulfilled due to bad syntax" ? I don't find anything suitable for a specific lack of parameter ;

Yes, `400 Bad Request` is exactly how a server points out the client has made an error. The description from the [IETF](http://tools.ietf.org/html/rfc7231#section-6.5.1):

```
The 400 (Bad Request) status code indicates that the server cannot or
will not process the request due to something that is perceived to be
a client error (e.g., malformed request syntax, invalid request
message framing, or deceptive request routing).
```

In reality this means `400 Bad Request` should be used in the PhotoBackup API where there now is [401](https://github.com/PhotoBackup/api/blob/master/v2/api.raml#L36-L37) (no `upfile` has nothing to do with authorisation) and [411](https://github.com/PhotoBackup/api/blob/master/v2/api.raml#L42-L43) (a faulty `filesize` has nothing to do with the HTTP request Content-Length).

Completely changing the HTTP status codes is a breaking API change however, and should only be done for the v3 API. For now it is more important to clear up the way the current API works (even if that’s with some mixed up status codes).
